<html>
<title>Atlas Project</title>
<FRAMESET ROWS="120,*" FRAMESPACING="0" FRAMEBORDER="0" BORDER="0">
	<FRAME SRC="Prueba.php" NAME="CABEZERA_FILTRADOS">
 	<FRAMESET COLS="400,*" FRAMESPACING="0" FRAMEBORDER="1" BORDER="1">
		
		<FRAME SRC="Prueba2.php" NAME="MENU">
		<FRAME SRC="Prueba3.php" NAME="CONTENIDO"> 
	</FRAMESET>
		<!--<FRAME SRC="pie.php" NAME="pie">	-->	
<NOFRAMES>
<body>

<p><I>ESTE DOCUMENTO REQUIERE UN NAVEGADOR QUE VISUALICE FRAMES.</I></P>
</body>
</NOFRAMES>
</FRAMESET>
</html>
